<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
    <ProjectReference Include="..\..\Bootstrapper\RouteFlow.Api\RouteFlow.Api.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>5b8de7d3-1e97-4165-9bb3-cb4975b76bf7</UserSecretsId>
  </PropertyGroup>

</Project>
